#!/usr/bin/env bash
usage() {
	echo "Usage: $0 <battery_id> <threshold> <wait>"
	echo -e '\tbattery_id >= 0'
	echo -e '\tthreshold > 0'
	echo -e '\twait >= 0'
}

battery_dir="/sys/class/power_supply/BAT$1/"

(( $# < 2 )) && usage && exit 1
[[ ! -d $battery_dir ]] && usage && exit 2
(( $2 < 1 )) && usage && exit 3
(( $3 < 0 )) && usage && exit 4

status=$(cat $battery_dir'status')
while true; do
	case $status in
		Discharging)
			capacity=$(cat $battery_dir'capacity')
			(( $capacity < $2 )) && i3-nagbar -m 'Low battery!'
			#inotifywait -e modify $battery_dir'capacity'
			sleep $3
			status=$(cat $battery_dir'status')
			;;
		*)
			#inotifywait -e modify $battery_dir'status'
			sleep $3
			status=$(cat $battery_dir'status')
			;;
	esac
done
