#!/usr/bin/env bash
usage() {
	echo "Usage: $0 <battery_id> <threshold> <wait>"
	echo -e '\tbattery_id >= 0'
	echo -e '\tthreshold > 0'
	echo -e '\twait >= 0'
}

battery_dir="/sys/class/power_supply/BAT$1/"

(( $# != 3 )) && usage && exit 1
[[ ! -d $battery_dir ]] && usage && exit 2
(( $2 < 1 )) && usage && exit 3
(( $3 < 0 )) && usage && exit 4

status=$(cat $battery_dir'status')
while true; do
	if [[ $status == 'Discharging' ]]; then
		capacity=$(cat $battery_dir'capacity')
		(( $capacity < $2 )) && i3-nagbar -m 'Low battery!'
		sleep $3
		status=$(cat $battery_dir'status')
	else
		sleep $3
		status=$(cat $battery_dir'status')
	fi
done
